---

- hosts: webserver
  tasks:

    - name: install the latest version of Nginx
      yum:
        name: nginx
        state: latest

    - name: start nginx
      service:
        name: nginx
        state: started

    - name: Install ntp
      yum:
        name: ntp
        state: present

    - name: Start Nginx
      service:
        name: ntp
        state: restarted
