---

- name: Install httpd
  yum: name=httpd state=present
  tags: web

- name: start firewalld
  service: name=firewalld state=started enabled=yes

- name: insert filrewalld rule
  firewalld: port=80/tcp permanent=true state=enabled immediate=yes

- name: copy html file
  template: src=index.html dest=/var/www/html

- name: httpd service start
  service: name=httpd state=started enabled=yes 

